### ISSUE TITLE
Service

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/betterDime#2]
- [x] Backend-Implementation fertig
- [x] Frontend-Implementation fertig
- [x] DB-Migrationsskript aktualisiert

**Comment by tourn** [comment]
Die Services werden via ServiceRate mit RateGroups (Kanton, Private) verbunden (m:n). Je nach Constraints kann das Formular simpler gestaltet werden:

Einfachster Fall: Wenn jeder Service mit jeder RateGroup verbunden ist, kann im Formular eine fixe Tabelle mit allen zu spezifizierenden RateGroups aufgelistet werden.

![image](https://user-images.githubusercontent.com/2150982/47549877-b6343380-d8fd-11e8-9f29-865373537c3a.png)


Ist dies nicht der Fall, wenn also einige Services nur mit ausgewählten RateGroups verbunden sind, muss das Formular wie in Dime das Hinzufügen/Löschen von ServiceRates ermöglichen. Zusätzlich muss dann auch die [Offerte|Projekt|Rechnnung]-Assoziation mit Services wieder sicher stellen, dass die konfigurierten RateGroups des Services kompatibel sind. (Passiert in Dime so, könnte aber vielleicht vereinfacht werden.)

![image](https://user-images.githubusercontent.com/2150982/47549845-a1f03680-d8fd-11e8-96d1-8d069c197cea.png)

**Comment by andyundso** [comment]
ServiceRates soll automatisch für alle RateGroups erstellt werden.

**Comment by andyundso** [comment]
Ich habe mit Andi noch besprochen, dass wir kommenden Dienstag (etwa) mit Manu die Services aufräumen bzgl. RateUnitTypes und allg., was noch verwendet wird und was nicht.
