### ISSUE TITLE
Pflegepläne ins Dime integrieren

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/betterDime#26]
Reporter: Dani Latzer

---

Die Pflegepläne aus der existierenden Filemaker-Applikation sollen ins Dime integriert werden. Gemäss Andi sollen wir uns auch mit Manu unterhalten, wie er sich das künftig im Dime vorstellt.

**Comment by skius** [comment]
Stand 28.3.2019:
Integration ins Dime macht keinen Sinn, da keine Überschneidung der Daten besteht.
Fazit: Eventuell separates Tool
