### ISSUE TITLE
Zeiterfassungsansicht

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/betterDime#29]
Die Zeiterfassungsansicht könnte ggf. noch optimiert werden. Zoho Projects hat eine schöne Referenzimplementation:

![image](https://user-images.githubusercontent.com/7010698/48008963-03dd4700-e11b-11e8-8b60-ba61bdba7822.png)

![image](https://user-images.githubusercontent.com/7010698/48008977-0d66af00-e11b-11e8-91e4-61f2739d3df4.png)

![image](https://user-images.githubusercontent.com/7010698/48008998-18b9da80-e11b-11e8-956d-93bf40a9b377.png)

![image](https://user-images.githubusercontent.com/7010698/48009032-253e3300-e11b-11e8-9e32-5a09656715e2.png)

Ggf. noch selber etwas brainstormen und bei Andi fragen, wo er persönlich Optimierungspotenzial sieht.

**Comment by tourn** [comment]
Optimieren für Mobile: Persönliche Zeiterfassung sollte möglich sein. (Ev. kann man hier auch eine spezielle Mobile-View mit weniger Features implementieren.)

**Comment by andyundso** [comment]
Erste Version der Ansicht ist nun implementiert. Folgende Dinge könnte man im Absprache mit Andi optimieren:
 - In der mobilen Ansicht könnten die TimetrackFilter in einem Collapsible gerendert werden bzw. die Collapsible immer als geschlossen gerendert werden.
- Pro Gruppe wird ein Total angezeigt an verbuchten Gütern und Stunden.
- "Speichern und weiter"-Knopf für Alex im TimetrackFormDialog.
- Standardgruppierung (Mitarbeiter, Projekt oder Service) als Einstellung auf dem Profil verfügbar machen.
- Sobald eine neue Leistung gebucht wurde, die aktuellen Filter (Mitarbeiter, Projekt und Service) in den TimetrackFilter zurückpopulieren.
- Letzte Einstellungen des TimetrackFormDialogs speichern in EmployeeSettings.

**Comment by tourn** [comment]
TODO

- [ ] "Speichern und offen lassen" Button für Erfassungsdialog
- [ ] Multi Select von Mitarbeitern im Erfassungsdialog
- [ ] Projektkommentar (auch?) im Zeiterfassungsdialog eingeben
- [ ] Multi-Select und verschieben von Einträgen
