### ISSUE TITLE
Drag & Drop für Sortierung der Positionen verwenden

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/betterDime#38]
Reporter: Zivi

---

Für die Sortierung der Positionen bei der Offerte / beim Projekt / bei der Rechnung soll künftig Drag / Drop verwendet werden, anstatt die Sortierung über das Zahlenfeld zu lösen.

**Comment by tourn** [comment]
Offerten und Rechnungen werden jetzt mit Drag and Drop umsortiert. Rechnungen konnten bisher noch gar nicht umsortiert werden. Sollte das jemals benötigt werden, kann der neue `DraggableTableBody` auch dort einfach eingeklinkt werden.
