### ISSUE TITLE
Rechnung ohne Projekt erlaubt

### ISSUE THREAD

**Issue by TheFehr** [stiftungswo/betterDime#56]

**Comment by TheFehr** [comment]
Rechnungen sollten nur mit Projekten möglich sein

**Comment by andyundso** [comment]
Kann hier ergänzen, dass wir beim Dime-Rewrite Andi explizit gefragt haben, ob dies auch künftig gewünscht sei, dass man Rechnungen ohne Projekt erstellen kann. Er hat dies mit "Ja" beantwortet, da es z.B. Rechnungen gibt im Dime, bei welchem man von Zivis Spesen zurückfordert oder einem Besteller aus dem Online-Shop einen Katalog verrechnet. Daher scheint es mir etwas überflüssig, extra ein ganzes Projekt anlegen zu müssen, nur um eine Rechnung zu machen. Aber evt. habe ich da etwas verpasst im Kontext von den Auswertungen, welche durch dieses Vorgehen natürlich "etwas" verfälscht werden.
